SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MusicInfo](
	[MusicInfoID] [int] IDENTITY(1,1) NOT NULL,
	[Titulo] [nvarchar](50) NOT NULL,
	[Genero] [int] NULL,
	[Duracao] [int] NULL,
	[Letra] [text] NULL,
	[BandaID] [int] NULL,
 CONSTRAINT [PK__tmp_ms_x__68835C14EB304E3C] PRIMARY KEY CLUSTERED 
(
	[MusicInfoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


