SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AlbumInfo](
	[AlbumInfoID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Year] [int] NOT NULL,
	[Description] [nvarchar](100) NULL,
	[Editora] [nvarchar](50) NULL,
 CONSTRAINT [PK__tmp_ms_x__F97D8A8D06563846] PRIMARY KEY CLUSTERED 
(
	[AlbumInfoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
