SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PlaylistInfo](
	[PlaylistInfoID] [int] IDENTITY(1,1) NOT NULL,
	[User] [int] NOT NULL,
	[Public] [bit] NOT NULL,
	[Nome] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__tmp_ms_x__6A5DC719DEDDE45D] PRIMARY KEY CLUSTERED 
(
	[PlaylistInfoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


