SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Music](
	[MusicID] [int] IDENTITY(1,1) NOT NULL,
	[MusicInfo] [int] NOT NULL,
	[Artist] [int] NOT NULL,
	[Musico] [bit] NOT NULL,
	[Compositor] [bit] NOT NULL,
 CONSTRAINT [PK__tmp_ms_x__11F840E06A0389BE] PRIMARY KEY CLUSTERED 
(
	[MusicID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


